/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewUrnaEleitoral;

/**
 *
 * @author batcomputador
 */
public class viewVotos extends javax.swing.JFrame {

    /**
     * Creates new form viewVotos
     */
    public viewVotos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jTabbedPanePresidente = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        totalVotosPresLabel = new javax.swing.JLabel();
        jSeparator32 = new javax.swing.JSeparator();
        progBarCand1 = new javax.swing.JProgressBar();
        candidato1Label = new javax.swing.JLabel();
        candidato2Label = new javax.swing.JLabel();
        progBarCand2 = new javax.swing.JProgressBar();
        qtdVotos1 = new javax.swing.JLabel();
        jSeparator34 = new javax.swing.JSeparator();
        qtdVotos2 = new javax.swing.JLabel();
        jSeparator35 = new javax.swing.JSeparator();
        jLabel90 = new javax.swing.JLabel();
        candidato3Label = new javax.swing.JLabel();
        progBarCand3 = new javax.swing.JProgressBar();
        qtdVotos3 = new javax.swing.JLabel();
        candidato4Label = new javax.swing.JLabel();
        jSeparator36 = new javax.swing.JSeparator();
        progBarCand4 = new javax.swing.JProgressBar();
        qtdVotos4 = new javax.swing.JLabel();
        jSeparator37 = new javax.swing.JSeparator();
        candidato5Label = new javax.swing.JLabel();
        progBarCand5 = new javax.swing.JProgressBar();
        qtdVotos5 = new javax.swing.JLabel();
        jSeparator38 = new javax.swing.JSeparator();
        jLabel100 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        totalVotosGovLabel = new javax.swing.JLabel();
        jSeparator33 = new javax.swing.JSeparator();
        progBarCandGov1 = new javax.swing.JProgressBar();
        candidatoGov1Label = new javax.swing.JLabel();
        candidatoGov2Label = new javax.swing.JLabel();
        progBarCandGov2 = new javax.swing.JProgressBar();
        qtdVotosGov1 = new javax.swing.JLabel();
        jSeparator39 = new javax.swing.JSeparator();
        qtdVotosGov2 = new javax.swing.JLabel();
        jSeparator40 = new javax.swing.JSeparator();
        jLabel91 = new javax.swing.JLabel();
        candidatoGov3Label = new javax.swing.JLabel();
        progBarCandGov3 = new javax.swing.JProgressBar();
        qtdVotosGov3 = new javax.swing.JLabel();
        candidatoGov4Label = new javax.swing.JLabel();
        jSeparator41 = new javax.swing.JSeparator();
        progBarCandGov4 = new javax.swing.JProgressBar();
        qtdVotosGov4 = new javax.swing.JLabel();
        jSeparator42 = new javax.swing.JSeparator();
        candidatoGov5Label = new javax.swing.JLabel();
        progBarCandGov5 = new javax.swing.JProgressBar();
        qtdVotosGov5 = new javax.swing.JLabel();
        jSeparator43 = new javax.swing.JSeparator();
        jLabel104 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        totalVotosPrefLabel = new javax.swing.JLabel();
        jSeparator44 = new javax.swing.JSeparator();
        progBarCandPref1 = new javax.swing.JProgressBar();
        candidatoPref1Label = new javax.swing.JLabel();
        candidatoPref2Label = new javax.swing.JLabel();
        progBarCandPref2 = new javax.swing.JProgressBar();
        qtdVotosPref1 = new javax.swing.JLabel();
        jSeparator45 = new javax.swing.JSeparator();
        qtdVotosPref2 = new javax.swing.JLabel();
        jSeparator46 = new javax.swing.JSeparator();
        jLabel92 = new javax.swing.JLabel();
        candidatoPref3Label = new javax.swing.JLabel();
        progBarCandPref3 = new javax.swing.JProgressBar();
        qtdVotosPref3 = new javax.swing.JLabel();
        candidatoPref4Label = new javax.swing.JLabel();
        jSeparator47 = new javax.swing.JSeparator();
        progBarCandPref4 = new javax.swing.JProgressBar();
        qtdVotosPref4 = new javax.swing.JLabel();
        jSeparator48 = new javax.swing.JSeparator();
        candidatoPref5Label = new javax.swing.JLabel();
        progBarCandPref5 = new javax.swing.JProgressBar();
        qtdVotosPref5 = new javax.swing.JLabel();
        jSeparator49 = new javax.swing.JSeparator();
        jLabel108 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        jLabel110 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jLabel15.setText("jLabel15");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPanePresidente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPanePresidente.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        totalVotosPresLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        totalVotosPresLabel.setText("Votos");

        candidato1Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        candidato1Label.setText("Candidato 1");

        candidato2Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        candidato2Label.setText("Candidato 2");

        qtdVotos1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        qtdVotos1.setText("Qtd. votos");

        qtdVotos2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        qtdVotos2.setText("Qtd. votos");

        jLabel90.setText("#1");

        candidato3Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        candidato3Label.setText("Candidato 3");

        qtdVotos3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        qtdVotos3.setText("Qtd. votos");

        candidato4Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        candidato4Label.setText("Candidato 4");

        qtdVotos4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        qtdVotos4.setText("Qtd. votos");

        candidato5Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        candidato5Label.setText("Candidato 5");

        qtdVotos5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        qtdVotos5.setText("Qtd. votos");

        jLabel100.setText("#2");

        jLabel101.setText("#4");

        jLabel102.setText("#5");

        jLabel103.setText("#3");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalVotosPresLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator32, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel90)
                                            .addComponent(jLabel100, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(qtdVotos1)
                                            .addComponent(candidato1Label)
                                            .addComponent(progBarCand1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(candidato2Label)
                                            .addComponent(progBarCand2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jSeparator34, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(qtdVotos2)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel101, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel102, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel103, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(qtdVotos5)
                                            .addComponent(candidato5Label)
                                            .addComponent(qtdVotos4)
                                            .addComponent(progBarCand4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                                            .addComponent(candidato4Label)
                                            .addComponent(qtdVotos3)
                                            .addComponent(candidato3Label)
                                            .addComponent(jSeparator35)
                                            .addComponent(progBarCand3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jSeparator36)
                                            .addComponent(jSeparator37)
                                            .addComponent(progBarCand5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addContainerGap())
                    .addComponent(jSeparator38, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalVotosPresLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator32, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(candidato1Label)
                    .addComponent(jLabel90))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progBarCand1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qtdVotos1)
                .addGap(2, 2, 2)
                .addComponent(jSeparator34, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(candidato2Label)
                    .addComponent(jLabel100))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progBarCand2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qtdVotos2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator35, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(candidato3Label)
                    .addComponent(jLabel103))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(progBarCand3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qtdVotos3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator36, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(candidato4Label)
                    .addComponent(jLabel101))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progBarCand4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qtdVotos4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator37, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(candidato5Label)
                    .addComponent(jLabel102))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(progBarCand5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qtdVotos5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator38, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Resultado", jPanel5);

        jTabbedPanePresidente.addTab("Presidente", jTabbedPane2);

        totalVotosGovLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        totalVotosGovLabel.setText("Votos");

        candidatoGov1Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        candidatoGov1Label.setText("Candidato 1");

        candidatoGov2Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        candidatoGov2Label.setText("Candidato 2");

        qtdVotosGov1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        qtdVotosGov1.setText("Qtd. votos");

        qtdVotosGov2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        qtdVotosGov2.setText("Qtd. votos");

        jLabel91.setText("#1");

        candidatoGov3Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        candidatoGov3Label.setText("Candidato 3");

        qtdVotosGov3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        qtdVotosGov3.setText("Qtd. votos");

        candidatoGov4Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        candidatoGov4Label.setText("Candidato 4");

        qtdVotosGov4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        qtdVotosGov4.setText("Qtd. votos");

        candidatoGov5Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        candidatoGov5Label.setText("Candidato 5");

        qtdVotosGov5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        qtdVotosGov5.setText("Qtd. votos");

        jLabel104.setText("#2");

        jLabel105.setText("#4");

        jLabel106.setText("#5");

        jLabel107.setText("#3");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalVotosGovLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator33, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel91)
                                            .addComponent(jLabel104, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(qtdVotosGov1)
                                            .addComponent(candidatoGov1Label)
                                            .addComponent(progBarCandGov1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(candidatoGov2Label)
                                            .addComponent(progBarCandGov2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jSeparator39, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(qtdVotosGov2)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel105, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel106, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel107, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(qtdVotosGov5)
                                            .addComponent(candidatoGov5Label)
                                            .addComponent(qtdVotosGov4)
                                            .addComponent(progBarCandGov4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                                            .addComponent(candidatoGov4Label)
                                            .addComponent(qtdVotosGov3)
                                            .addComponent(candidatoGov3Label)
                                            .addComponent(jSeparator40)
                                            .addComponent(progBarCandGov3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jSeparator41)
                                            .addComponent(jSeparator42)
                                            .addComponent(progBarCandGov5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addContainerGap())
                    .addComponent(jSeparator43, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalVotosGovLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator33, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(candidatoGov1Label)
                    .addComponent(jLabel91))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progBarCandGov1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qtdVotosGov1)
                .addGap(2, 2, 2)
                .addComponent(jSeparator39, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(candidatoGov2Label)
                    .addComponent(jLabel104))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progBarCandGov2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qtdVotosGov2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator40, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(candidatoGov3Label)
                    .addComponent(jLabel107))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(progBarCandGov3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qtdVotosGov3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator41, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(candidatoGov4Label)
                    .addComponent(jLabel105))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progBarCandGov4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qtdVotosGov4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator42, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(candidatoGov5Label)
                    .addComponent(jLabel106))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(progBarCandGov5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qtdVotosGov5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator43, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Resultado", jPanel6);

        jTabbedPanePresidente.addTab("Governador", jTabbedPane3);

        totalVotosPrefLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        totalVotosPrefLabel.setText("Votos");

        candidatoPref1Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        candidatoPref1Label.setText("Candidato 1");

        candidatoPref2Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        candidatoPref2Label.setText("Candidato 2");

        qtdVotosPref1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        qtdVotosPref1.setText("Qtd. votos");

        qtdVotosPref2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        qtdVotosPref2.setText("Qtd. votos");

        jLabel92.setText("#1");

        candidatoPref3Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        candidatoPref3Label.setText("Candidato 3");

        qtdVotosPref3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        qtdVotosPref3.setText("Qtd. votos");

        candidatoPref4Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        candidatoPref4Label.setText("Candidato 4");

        qtdVotosPref4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        qtdVotosPref4.setText("Qtd. votos");

        candidatoPref5Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        candidatoPref5Label.setText("Candidato 5");

        qtdVotosPref5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        qtdVotosPref5.setText("Qtd. votos");

        jLabel108.setText("#2");

        jLabel109.setText("#4");

        jLabel110.setText("#5");

        jLabel111.setText("#3");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalVotosPrefLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator44, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel92)
                                            .addComponent(jLabel108, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(qtdVotosPref1)
                                            .addComponent(candidatoPref1Label)
                                            .addComponent(progBarCandPref1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(candidatoPref2Label)
                                            .addComponent(progBarCandPref2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jSeparator45, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(qtdVotosPref2)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel109, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel110, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel111, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(qtdVotosPref5)
                                            .addComponent(candidatoPref5Label)
                                            .addComponent(qtdVotosPref4)
                                            .addComponent(progBarCandPref4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                                            .addComponent(candidatoPref4Label)
                                            .addComponent(qtdVotosPref3)
                                            .addComponent(candidatoPref3Label)
                                            .addComponent(jSeparator46)
                                            .addComponent(progBarCandPref3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jSeparator47)
                                            .addComponent(jSeparator48)
                                            .addComponent(progBarCandPref5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addContainerGap())
                    .addComponent(jSeparator49, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalVotosPrefLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator44, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(candidatoPref1Label)
                    .addComponent(jLabel92))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progBarCandPref1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qtdVotosPref1)
                .addGap(2, 2, 2)
                .addComponent(jSeparator45, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(candidatoPref2Label)
                    .addComponent(jLabel108))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progBarCandPref2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qtdVotosPref2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator46, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(candidatoPref3Label)
                    .addComponent(jLabel111))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(progBarCandPref3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qtdVotosPref3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator47, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(candidatoPref4Label)
                    .addComponent(jLabel109))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progBarCandPref4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qtdVotosPref4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator48, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(candidatoPref5Label)
                    .addComponent(jLabel110))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(progBarCandPref5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qtdVotosPref5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator49, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Resultado", jPanel7);

        jTabbedPanePresidente.addTab("Prefeito", jTabbedPane4);

        getContentPane().add(jTabbedPanePresidente, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewVotos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewVotos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewVotos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewVotos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewVotos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel candidato1Label;
    public static javax.swing.JLabel candidato2Label;
    public static javax.swing.JLabel candidato3Label;
    public static javax.swing.JLabel candidato4Label;
    public static javax.swing.JLabel candidato5Label;
    public static javax.swing.JLabel candidatoGov1Label;
    public static javax.swing.JLabel candidatoGov2Label;
    public static javax.swing.JLabel candidatoGov3Label;
    public static javax.swing.JLabel candidatoGov4Label;
    public static javax.swing.JLabel candidatoGov5Label;
    public static javax.swing.JLabel candidatoPref1Label;
    public static javax.swing.JLabel candidatoPref2Label;
    public static javax.swing.JLabel candidatoPref3Label;
    public static javax.swing.JLabel candidatoPref4Label;
    public static javax.swing.JLabel candidatoPref5Label;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator32;
    private javax.swing.JSeparator jSeparator33;
    private javax.swing.JSeparator jSeparator34;
    private javax.swing.JSeparator jSeparator35;
    private javax.swing.JSeparator jSeparator36;
    private javax.swing.JSeparator jSeparator37;
    private javax.swing.JSeparator jSeparator38;
    private javax.swing.JSeparator jSeparator39;
    private javax.swing.JSeparator jSeparator40;
    private javax.swing.JSeparator jSeparator41;
    private javax.swing.JSeparator jSeparator42;
    private javax.swing.JSeparator jSeparator43;
    private javax.swing.JSeparator jSeparator44;
    private javax.swing.JSeparator jSeparator45;
    private javax.swing.JSeparator jSeparator46;
    private javax.swing.JSeparator jSeparator47;
    private javax.swing.JSeparator jSeparator48;
    private javax.swing.JSeparator jSeparator49;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPanePresidente;
    public static javax.swing.JProgressBar progBarCand1;
    public static javax.swing.JProgressBar progBarCand2;
    public static javax.swing.JProgressBar progBarCand3;
    public static javax.swing.JProgressBar progBarCand4;
    public static javax.swing.JProgressBar progBarCand5;
    public static javax.swing.JProgressBar progBarCandGov1;
    public static javax.swing.JProgressBar progBarCandGov2;
    public static javax.swing.JProgressBar progBarCandGov3;
    public static javax.swing.JProgressBar progBarCandGov4;
    public static javax.swing.JProgressBar progBarCandGov5;
    public static javax.swing.JProgressBar progBarCandPref1;
    public static javax.swing.JProgressBar progBarCandPref2;
    public static javax.swing.JProgressBar progBarCandPref3;
    public static javax.swing.JProgressBar progBarCandPref4;
    public static javax.swing.JProgressBar progBarCandPref5;
    public static javax.swing.JLabel qtdVotos1;
    public static javax.swing.JLabel qtdVotos2;
    public static javax.swing.JLabel qtdVotos3;
    public static javax.swing.JLabel qtdVotos4;
    public static javax.swing.JLabel qtdVotos5;
    public static javax.swing.JLabel qtdVotosGov1;
    public static javax.swing.JLabel qtdVotosGov2;
    public static javax.swing.JLabel qtdVotosGov3;
    public static javax.swing.JLabel qtdVotosGov4;
    public static javax.swing.JLabel qtdVotosGov5;
    public static javax.swing.JLabel qtdVotosPref1;
    public static javax.swing.JLabel qtdVotosPref2;
    public static javax.swing.JLabel qtdVotosPref3;
    public static javax.swing.JLabel qtdVotosPref4;
    public static javax.swing.JLabel qtdVotosPref5;
    public static javax.swing.JLabel totalVotosGovLabel;
    public static javax.swing.JLabel totalVotosPrefLabel;
    public static javax.swing.JLabel totalVotosPresLabel;
    // End of variables declaration//GEN-END:variables
}
